spring:
  application:
    name: ${vcap.application.name:spring-a-gram-backend}
  data:
    rest:
      basePath: /api

server:
  port: 0  # Spring Boot randomly assigns a port number

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.address:localhost:8761}
  instance:
    leaseRenewalIntervalInSeconds: 5
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    ROOT: INFO
    com.gregturnquist.springagram: DEBUG
    org.hibernate.SQL: DEBUG

---
spring:
  profiles: cloud

eureka:
  instance:
    nonSecurePort: 80

---
spring:
  profiles: production
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
