spring:
  application:
    name: ${vcap.application.name:spring-a-gram-frontend}
  data:
    rest:
      basePath: /api

multipart:
  maxFileSize: 10Mb

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.address:localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

zuul:
  routes:
    api:
      path: /api/**
      serviceId: spring-a-gram-backend
      stripPrefix: false
    files:
      path: /files/**
      serviceId: spring-a-gram-mongodb-fileservice
      stripPrefix: false

logging:
  level:
    ROOT: INFO
    com.gregturnquist.springagram: DEBUG
    org.hibernate.SQL: DEBUG

---
spring:
  profiles: s3

zuul:
  routes:
    api:
      path: /api/**
      serviceId: spring-a-gram-backend
      stripPrefix: false
    files:
      path: /files/**
      serviceId: spring-a-gram-s3-fileservice
      stripPrefix: false

---
spring:
  profiles: cloud

eureka:
  instance:
    nonSecurePort: 80
